### PR TITLE
fix: StreamingServer statistics response `null`

### LINKED ISSUE #573: Statistics - When null is returned from the server, it causes an error
When the stream has loaded to 100%, core still tries to deserialise the statistics object from the server request and ends up with an Error instead of keeping the last known Statistics

Ensure that we:
- [ ] Keep the last known statistics #577 
- [x] Handle `null` as "stream has loaded fully" #576

### PR DESCRIPTION
**Pull request by elpiel**
Resolves #573
Fix the issue where the server returns a `null` json response for the `stats.json`.
Up until now it was throwing an error on deserialization

### CODE REVIEW

**Review by TheBeastLT — APPROVED** [review]

File: src/models/streaming_server.rs [hunk 1]
```diff
@@ -588,7 +590,8 @@ fn get_torrent_statistics<E: Env + 'static>(url: &Url, request: &StatisticsReque
         .body(())
         .expect("request builder failed");
     EffectFuture::Concurrent(
-        E::fetch::<_, Statistics>(request)
+        // `null`` can be returned when the stream has been loaded 100%
```
Comment (tymmesyde) [inline src/models/streaming_server.rs]: It's happening when the engine is destroyed for inactivity:
https://github.com/Stremio/enginefs/blob/8722f2ecf423fc98d529aff3d0db5864e501ba04/enginefs.js#L309
If it was downloaded to 100% and that the stream is paused, then played, it will create a new engine and return the correct stats

Comment (elpiel) [reply src/models/streaming_server.rs]: Fixed the comment.
